### ISSUE TITLE
generate_MaSIV_list fails silently with non numeric channel names

### ISSUE THREAD

**Issue by ablot** [BaselLaserMouse/StitchIt#104]
That means that the output of mergeChannels needs to be renamed to an arbitrary number. 

- [x] Check that masiv itself can handle arbitrary channel names
- [x]  If it cannot, change the regexp in generate_MaSIV_list to do only numeric only channel
- [x]  if it can, change the num2str and downward code to handle text.

Low priority since renaming the folder works fine

**Comment by ablot** [comment]
More precisions on the current behaviour:

Folders with a number in their name are used by `generate_MaSIV_list` but if `str2num(folderName)` fails, then the channel shows as `Ch` in masiv. Masiv can open this channel perfectly fine. So I guess I can tick the first box.

**Comment by raacampbell** [comment]
Yeah, I think we should try to get MaSIV to do that. Arbitrary channel numbers are annoying. Later you don't know what they are.

**Comment by ablot** [comment]
Done. Tested on linux. I think that I've replaced all the `[dir, '/', dir]` by `fullfile` except that used to write in the yml file. Hopefully that should solve #29 and still generate a file list with unix separators.
