### ISSUE TITLE
Failing to find the offset in sample TLX_tomato for many sections

### ISSUE THREAD

**Issue by raacampbell** [BaselLaserMouse/StitchIt#111]

**Comment by ablot** [comment]
Is it a scanimage issue or the automatic offset calculation that fails? If you put a few tif files somewhere I can have a look.

**Comment by raacampbell** [comment]
Auto offset. I think I have a fix. Will push soon. I just average first.

**Comment by raacampbell** [comment]
I think this fixes it: ff11c2a03d2006551038b90288eda56d9593acc2
