### ISSUE TITLE
Doc text for stitchAllChannels is poor and it produces an error when run without input args

### ISSUE THREAD

**Issue by raacampbell** [BaselLaserMouse/StitchIt#55]

**Comment by lguerard** [comment]
Hi,

I don't know if this was for you of for me, but I'll just give a bit more info :).

The way I wrote the StitchAllChannels function is to be used with at least the exp_root channels as argument. You can  then add the channels you want as a second argument.

As for the doc text, is that something I can fix ?

**Comment by raacampbell** [comment]
? I wrote it [two months ago](https://github.com/BaselLaserMouse/StitchIt/blob/master/code/stitching/stitchAllChannels.m) ?

**Comment by lguerard** [comment]
Oops sorry, I thought it was the makeCompositeOfPlane function. My bad... :/

**Comment by raacampbell** [comment]
Ha, ha. I see.

**Comment by raacampbell** [comment]
Done:  e29cff0
