### ISSUE TITLE
preProcessTiles channel select is problematic 

### ISSUE THREAD

**Issue by raacampbell** [BaselLaserMouse/StitchIt#68]
The tile stats are generated via preProcessTiles. If the user asks for a subset of channels to be processed for, say, illumination correction, then the tile stats will contain only those channels. This is a potentially problematic situation. Better approaches might be:

* Tile stats is calculated separately and based on all channels.
* We always calculate parameters for all available channels. 
* We have one tileStats file per channel. 

I've not actually run into a problem yet, but this needs watching.

**Comment by ablot** [comment]
I'd close that. The dev branch and the si offset should fix the issue.
