### ISSUE TITLE
Preview scan crash if slicing parameters are wrong

### ISSUE THREAD

**Issue by ablot** [BaselLaserMouse/StitchIt#84]
Steps to reproduce the bug:
- start baking tray
- set the number of slice to do to something too large
- click on preview scan
The image in the preview scan will be removed, then a pop up will warn that baking tray can do at most XX slices. 
- Put a reasonable number of slices
- Click on preview again
matlab will return an error when trying to remove the image in the preview scan (since there is nothing left)

Current hack:
stop and start again the GUI

Potential fix:
- On pressing preview, skip the slice check (both number of slice and speed or thickness difference). might be good to do anyway but doesn't really fix the bug
- On pressing preview, test if channel image exist before erasing it

**Comment by raacampbell** [comment]
Moved to [BakingTray issue tracker](https://github.com/BaselLaserMouse/BakingTray/issues/83)
