### ISSUE TITLE
I see new messages saying "Skipping illumination correction" during syncAndCrunch

### ISSUE THREAD

**Issue by raacampbell** [BaselLaserMouse/StitchIt#89]
I don't recognize these. Maybe they are just new messages from the new `preProcessTiles`, but should check to make sure it's not skipping stuff it should be doing.

**Comment by ablot** [comment]
It should be printed if a slice for which the average have already been generated is going through `preProcessTiles` again. But it just checks:
```
length(sectionsToProcess)==1 && sectionsToProcess==0 && exist(aveDir,'dir') && all(cellfun(@exist, chanDirs))
```

Maybe it should be clearer. "Average folder already exists. Skipping illumination correction" ?

**Comment by ablot** [comment]
Or should I just not display anything for section already preProcessed?

**Comment by raacampbell** [comment]
No harm displaying a message.
